ARG NODE_IMAGE=node:24.15.0-alpine3.23

FROM ${NODE_IMAGE}

WORKDIR /app

# Required for some Next.js native deps on Alpine
RUN apk add --no-cache libc6-compat

EXPOSE 3000

CMD ["npm", "run", "dev"]
