ARG PHP_IMAGE=php:8.4.20-fpm-alpine3.23
ARG COMPOSER_IMAGE=composer:2.9.7

FROM ${COMPOSER_IMAGE} AS composer

FROM ${PHP_IMAGE}

WORKDIR /var/www/html

RUN apk add --no-cache \
    bash \
    curl \
    git \
    icu-dev \
    libzip-dev \
    oniguruma-dev \
    postgresql-dev \
    unzip \
    zip \
    linux-headers \
    $PHPIZE_DEPS \
    && docker-php-ext-install \
      intl \
      mbstring \
      pcntl \
      pdo \
      pdo_pgsql \
      zip \
      opcache \
    && pecl install redis xdebug \
    && docker-php-ext-enable redis xdebug

COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY ./infra/php/php.dev.ini /usr/local/etc/php/conf.d/99-supportflow.ini

COPY ./infra/docker/api/entrypoint.dev.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 9000

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php-fpm"]
