ARG PHP_IMAGE=php:8.4.20-fpm-alpine3.23
ARG COMPOSER_IMAGE=composer:2.9.7

FROM ${COMPOSER_IMAGE} AS composer

FROM ${PHP_IMAGE} AS base

WORKDIR /var/www/html

RUN apk add --no-cache \
    bash \
    curl \
    git \
    icu-dev \
    libzip-dev \
    oniguruma-dev \
    postgresql-dev \
    unzip \
    zip \
    linux-headers \
    $PHPIZE_DEPS \
    && docker-php-ext-install \
      intl \
      mbstring \
      pcntl \
      pdo \
      pdo_pgsql \
      zip \
      opcache \
    && pecl install redis \
    && docker-php-ext-enable redis

COPY --from=composer /usr/bin/composer /usr/bin/composer

COPY ./infra/php/php.prod.ini /usr/local/etc/php/conf.d/99-supportflow.ini
COPY ./infra/php/opcache.ini  /usr/local/etc/php/conf.d/10-opcache.ini

COPY ./apps/api/composer.json ./apps/api/composer.lock ./

RUN composer install \
    --no-dev \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader \
    --no-scripts

COPY ./apps/api .

RUN composer dump-autoload --optimize \
    && php artisan package:discover --ansi || true \
    && chown -R www-data:www-data storage bootstrap/cache

COPY ./infra/docker/api/entrypoint.prod.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER www-data

EXPOSE 9000

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php-fpm"]
